TARGET = main.elf

COMMAND_MAP_DIR = ./commandMap
COMMAND_MAP_SRC = $(COMMAND_MAP_DIR)/src
COMMAND_MAP_INC = $(COMMAND_MAP_DIR)/inc
COMMAND_MAP_TEST = $(COMMAND_MAP_DIR)/test

CMSIS_DIR = ./CMSIS
CORE_SUPPORT_DIR = $(CMSIS_DIR)/CM3/CoreSupport
DEVICE_SUPPORT_DIR = $(CMSIS_DIR)/CM3/DeviceSupport/ST/STM32F10x

CC = arm-none-eabi-gcc

CCFLAGS += -mcpu=cortex-m3
CCFLAGS += -mthumb
CCFLAGS += -I$(COMMAND_MAP_DIR)/inc
CCFLAGS += -I$(CORE_SUPPORT_DIR)
CCFLAGS += -I$(DEVICE_SUPPORT_DIR)
CCFLAGS += --specs=nosys.specs
CCFLAGS += -g

INPUT += main.c
INPUT += $(DEVICE_SUPPORT_DIR)/startup/gcc_ride7/startup_stm32f10x_ld.s
INPUT += $(DEVICE_SUPPORT_DIR)/system_stm32f10x.c
INPUT += $(CORE_SUPPORT_DIR)/core_cm3.c
INPUT += $(COMMAND_MAP_SRC)/hash.c

LD = -T./linkerScript.ld

OUTPUT = -o $(TARGET)


TEST_CC = gcc

UNITY_DIR = ./Unity/src
UNITY = $(UNITY_DIR)/unity.c

TEST_CCFLAGS += -I$(COMMAND_MAP_INC)
TEST_CCFLAGS += -I$(COMMAND_MAP_TEST)
TEST_CCFLAGS += -I$(UNITY_DIR)
TEST_CCFLAGS += -g

HASH_TEST_TARGET = hashTest

HASH_TEST_INPUT = $(COMMAND_MAP_SRC)/hash.c
HASH_TEST_INPUT += $(COMMAND_MAP_TEST)/hashTest.c
HASH_TEST_INPUT += $(UNITY)

HASH_TEST_OUTPUT = -o $(HASH_TEST_TARGET)

COMMAND_TEST_TARGET = commandTest

COMMAND_TEST_INPUT = $(COMMAND_MAP_SRC)/command.c
COMMAND_TEST_INPUT += $(COMMAND_MAP_TEST)/commandTest.c
COMMAND_TEST_INPUT += $(UNITY)

COMMAND_TEST_OUTPUT = -o $(COMMAND_TEST_TARGET)

COMMAND_LIST_TEST_TARGET = commandListTest

COMMAND_LIST_TEST_INPUT = $(COMMAND_MAP_SRC)/command.c
COMMAND_LIST_TEST_INPUT += $(COMMAND_MAP_SRC)/commandList.c
COMMAND_LIST_TEST_INPUT += $(COMMAND_MAP_TEST)/commandListTest.c
COMMAND_LIST_TEST_INPUT += $(UNITY)

COMMAND_LIST_TEST_OUTPUT = -o $(COMMAND_LIST_TEST_TARGET)

COMMAND_MAP_TEST_TARGET = commandMapTest

COMMAND_MAP_TEST_INPUT = $(COMMAND_MAP_SRC)/command.c
COMMAND_MAP_TEST_INPUT += $(COMMAND_MAP_SRC)/commandList.c
COMMAND_MAP_TEST_INPUT += $(COMMAND_MAP_SRC)/commandMap.c
COMMAND_MAP_TEST_INPUT += $(COMMAND_MAP_TEST)/commandMapTest.c
COMMAND_MAP_TEST_INPUT += $(UNITY)

COMMAND_MAP_TEST_OUTPUT = -o $(COMMAND_MAP_TEST_TARGET)

main:
	$(CC) $(CCFLAGS) $(INPUT) $(LD) $(OUTPUT)

testHash:
	$(TEST_CC) $(TEST_CCFLAGS) $(HASH_TEST_INPUT) $(HASH_TEST_OUTPUT)
	./$(HASH_TEST_TARGET)

testCommand:
	$(TEST_CC) $(TEST_CCFLAGS) $(COMMAND_TEST_INPUT) $(COMMAND_TEST_OUTPUT)
	./$(COMMAND_TEST_TARGET)

testCommandList:
	$(TEST_CC) $(TEST_CCFLAGS) $(COMMAND_LIST_TEST_INPUT) $(COMMAND_LIST_TEST_OUTPUT)
	./$(COMMAND_LIST_TEST_TARGET)

testCommandMap:
	$(TEST_CC) $(TEST_CCFLAGS) $(COMMAND_MAP_TEST_INPUT) $(COMMAND_MAP_TEST_OUTPUT)
	./$(COMMAND_MAP_TEST_TARGET)